# Generated by Django 4.1.3 on 2022-11-27 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uploadedfile_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, max_length=500, null=True, verbose_name='About Me')),
                ('my_location', models.CharField(blank=True, max_length=30, null=True, verbose_name='My Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('profile_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile', to='accounts.uploadedfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
