# Generated by Django 4.1.3 on 2022-11-28 10:12

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='profile_photo'),
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
