# Generated by Django 4.1.3 on 2022-11-28 10:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_profile_photo'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='profile_photo',
        # ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='profile_photo'),
            preserve_default=False,
        ),
    ]
