# Generated by Django 4.1.3 on 2022-12-11 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0048_alter_bdservice_bdt_rate'),
        ('accounts', '0007_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('skills_in', models.ManyToManyField(related_name='skilled_contarctor', to='bds.bdservice')),
            ],
        ),
    ]
