# Generated by Django 4.1.3 on 2022-12-12 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0049_alter_bdservice_bdt_rate'),
        ('accounts', '0009_contractor_created_at_contractor_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='screening_done',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserPayout',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('payout_account', models.CharField(max_length=15, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('payout_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payout', to='bds.paymentmethod')),
            ],
        ),
    ]
