# Generated by Django 4.1.3 on 2022-12-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userpayout_payout_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='cv_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
