# Generated by Django 4.1.3 on 2022-11-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BdService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=152)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(editable=False, max_length=252, null=True)),
                ('from_name', models.CharField(editable=False, max_length=250, null=True)),
                ('from_email', models.EmailField(editable=False, max_length=254, null=True)),
                ('from_phone', models.CharField(editable=False, max_length=250, null=True)),
                ('from_location', models.TextField(editable=False, null=True)),
                ('service_title', models.CharField(editable=False, max_length=252, null=True)),
                ('service_description', models.TextField(editable=False, null=True)),
                ('service_image', models.TextField(editable=False, null=True)),
                ('service_option_title', models.CharField(editable=False, max_length=252, null=True)),
                ('service_option_description', models.TextField(editable=False, null=True)),
                ('to_name', models.CharField(editable=False, max_length=250, null=True)),
                ('to_email', models.EmailField(editable=False, max_length=254, null=True)),
                ('to_phone', models.CharField(editable=False, max_length=250, null=True)),
                ('shipping_address', models.TextField(editable=False, null=True)),
                ('payment_address', models.TextField(editable=False, null=True)),
                ('payment_method_title', models.CharField(editable=False, max_length=252, null=True)),
                ('payment_method_isntruction', models.TextField(editable=False, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=50, null=True)),
                ('order_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=50, null=True)),
                ('order_require', models.JSONField(editable=False, null=True)),
                ('order_require_file', models.JSONField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Order Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paid Amount')),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('payment_address', models.TextField(blank=True, null=True)),
                ('last_status', models.CharField(default='', max_length=152)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252)),
                ('instruction', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=252)),
                ('value', models.FloatField()),
                ('remarks', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordertransection', to='bds.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='methodstransection', to='bds.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=152)),
                ('apndix', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=300)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bds.bdservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='serice_image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bds.bdservice')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=152)),
                ('required', models.BooleanField(default=True)),
                ('maxlength', models.IntegerField(default=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('text', 'Text Box'), ('textarea', 'Text Area'), ('file', 'File')], default='', max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bds.bdservice')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('partialpaid', 'Partial Paid'), ('processing', 'Processing'), ('fullpaid', 'Full Paid'), ('pending', 'Pending'), ('progressing', 'Progressing'), ('hold', 'Hold'), ('complete', 'Complete')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus', to='bds.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequireFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_title', models.CharField(max_length=252)),
                ('title_value', models.FileField(blank=True, null=True, upload_to='require_files')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitemsfile', to='bds.order')),
                ('required_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitemserviceoptionfile', to='bds.requiredoption')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_title', models.CharField(max_length=252)),
                ('title_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='bds.order')),
                ('required_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitemserviceoption', to='bds.requiredoption')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orderpaymentmethod', to='bds.paymentmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orderservice', to='bds.bdservice'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orderoption', to='bds.serviceoptions'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderuser', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_remarks', models.TextField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bds.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='orderinvoice', to='bds.order'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField(max_length=300)),
                ('payment_address', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
