# Generated by Django 4.1.3 on 2022-11-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0002_serviceoptions_require_day_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('partialpaid', 'Partial Paid'), ('processing', 'Processing'), ('fullpaid', 'Full Paid'), ('pending', 'Pending'), ('progressing', 'Progressing'), ('hold', 'Hold'), ('complete', 'Complete'), ('unknown', 'Unknown')], default='', max_length=20),
        ),
    ]
