# Generated by Django 4.1.3 on 2022-11-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0004_order_tentative_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoptions',
            name='full_payment_need_before_delivery_date_day',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='tentative_delivery_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
