# Generated by Django 4.1.3 on 2022-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0006_remove_serviceoptions_full_payment_need_before_delivery_date_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_payment_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
