# Generated by Django 4.1.3 on 2022-11-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0008_invoice_due_payment_by_invoice_tentative_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoptions',
            name='partial_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
