# Generated by Django 4.1.3 on 2022-11-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0009_serviceoptions_partial_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='orderinvoice', to='bds.order'),
        ),
    ]
