# Generated by Django 4.1.3 on 2022-11-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0010_alter_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_payment_by',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tentative_delivery',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_status',
            field=models.CharField(default='', editable=False, max_length=152),
        ),
    ]
