# Generated by Django 4.1.3 on 2022-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0011_alter_invoice_due_payment_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_status',
            field=models.CharField(choices=[('partialpaid', 'Partial Paid'), ('processing', 'Processing'), ('fullpaid', 'Full Paid'), ('pending', 'Pending'), ('progressing', 'Progressing'), ('hold', 'Hold'), ('complete', 'Complete'), ('unknown', 'Unknown')], default='', max_length=152),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
