# Generated by Django 4.1.3 on 2022-11-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0012_alter_order_last_status_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tentative_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
