# Generated by Django 4.1.3 on 2022-12-02 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bds', '0015_alter_orderstatus_update_by'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='orderstatus',
        #     name='update_by',
        #     field=models.ForeignKey(blank=True, max_length=252, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        # ),
    ]
