# Generated by Django 4.1.3 on 2022-12-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0017_alter_orderstatus_update_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='update_by',
        ),
    ]
