# Generated by Django 4.1.3 on 2022-12-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0020_orderstatus_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='due',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
