# Generated by Django 4.1.3 on 2022-12-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0022_alter_order_last_status_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('partialpaid', 'Partial Paid'), ('processing', 'Processing'), ('fullpaid', 'Full Paid'), ('pending', 'Pending'), ('progressing', 'Progressing'), ('hold', 'Hold'), ('complete', 'Complete')], default=None, max_length=20, null=True),
        ),
    ]
