# Generated by Django 4.1.3 on 2022-12-04 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bds', '0023_orderstatus_remarks_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='due',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='update_by',
            field=models.ForeignKey(blank=True, editable=False, max_length=252, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
