# Generated by Django 4.1.3 on 2022-12-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0024_alter_orderstatus_due_alter_orderstatus_update_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerecord',
            name='due',
            field=models.IntegerField(default=0),
        ),
    ]
