# Generated by Django 4.1.3 on 2022-12-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0027_order_paying_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='update_by',
        ),
    ]
