# Generated by Django 4.1.3 on 2022-12-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0029_orderstatus_update_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='paying_commited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('processing', 'Processing'), ('pending', 'Pending'), ('progressing', 'Progressing'), ('patial_progressing', 'Partial Progressing'), ('hold', 'Hold'), ('complete', 'Complete')], default=None, max_length=20, null=True),
        ),
    ]
