# Generated by Django 4.1.3 on 2022-12-05 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0031_remove_order_paying_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('processing', 'Processing'), ('pending', 'Pending'), ('progressing', 'Progressing'), ('patial_progressing', 'Partial Progressing'), ('payment_reject', 'Payment Reject'), ('complete', 'Complete')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transection',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordertransection', to='bds.order'),
        ),
    ]
