# Generated by Django 4.1.3 on 2022-12-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0034_transection_type_alter_transection_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='order',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordertransection', to='bds.order'),
        ),
        migrations.AlterField(
            model_name='transection',
            name='paying_commited',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='transection',
            name='type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transection',
            name='value',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
