# Generated by Django 4.1.3 on 2022-12-05 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bds', '0035_alter_transection_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transuser', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='transection',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
