# Generated by Django 4.1.3 on 2022-12-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0037_rename_user_transection_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerecord',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoicerecord', to='bds.invoice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.FloatField(default=0, verbose_name='Order Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('processing', 'Processing'), ('pending', 'Pending'), ('progressing', 'Progressing'), ('patial_progressing', 'Partial Progressing'), ('payment_reject', 'Payment Reject'), ('complete', 'Complete'), ('over_due', 'Over Due')], default=None, max_length=20, null=True),
        ),
    ]
