# Generated by Django 4.1.3 on 2022-12-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0038_alter_invoicerecord_invoice_alter_order_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.FloatField(null=True),
        ),
    ]
