# Generated by Django 4.1.3 on 2022-12-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0039_alter_invoice_order_amount_alter_invoice_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(default=0, verbose_name='Order Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.IntegerField(default=0, verbose_name='Paid Amount'),
        ),
    ]
