# Generated by Django 4.1.3 on 2022-12-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0040_alter_invoice_order_amount_alter_invoice_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdservice',
            name='option_priceauto_calculate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('processing', 'Processing'), ('pending', 'Pending'), ('progressing', 'Progressing'), ('partial_progressing', 'Partial Progressing'), ('payment_reject', 'Payment Reject'), ('complete', 'Complete'), ('over_due', 'Over Due')], default=None, max_length=20, null=True),
        ),
    ]
