# Generated by Django 4.1.3 on 2022-12-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0041_bdservice_option_priceauto_calculate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bdservice',
            old_name='option_priceauto_calculate',
            new_name='option_price_auto_calculate',
        ),
    ]
