# Generated by Django 4.1.3 on 2022-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0042_rename_option_priceauto_calculate_bdservice_option_price_auto_calculate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdservice',
            name='bdt_rate',
            field=models.FloatField(default=101.8298),
        ),
    ]
