# Generated by Django 4.1.3 on 2022-12-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0044_alter_bdservice_bdt_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoptions',
            name='apndix',
            field=models.IntegerField(default=0, help_text='Original Cost or buying price'),
        ),
    ]
