# Generated by Django 4.1.3 on 2022-12-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0045_alter_serviceoptions_apndix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoptions',
            name='apndix',
            field=models.FloatField(default=0, help_text='Original Cost perday or buying price in default currency, curently USD'),
        ),
    ]
