# Generated by Django 4.1.3 on 2022-12-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0046_alter_serviceoptions_apndix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='due',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.FloatField(default=0, verbose_name='Order Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='due',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='serviceoptions',
            name='apndix',
            field=models.FloatField(default=0, help_text='Original Cost perday or buying price in default currency, curently USD', verbose_name='Perday Original Cost'),
        ),
        migrations.AlterField(
            model_name='transection',
            name='paying_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transection',
            name='value',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
