# Generated by Django 4.1.3 on 2022-12-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0047_alter_invoice_order_amount_alter_invoice_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdservice',
            name='bdt_rate',
            field=models.FloatField(default=101.9255, editable=False),
        ),
    ]
