# Generated by Django 4.1.3 on 2022-12-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0048_alter_bdservice_bdt_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdservice',
            name='bdt_rate',
            field=models.FloatField(default=102.2294, editable=False),
        ),
    ]
