# Generated by Django 4.1.3 on 2022-12-13 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bds', '0049_alter_bdservice_bdt_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdservice',
            name='bdt_rate',
            field=models.FloatField(default=102.4949, editable=False),
        ),
        migrations.CreateModel(
            name='PickedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_user_order', to='bds.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_order', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
