# Generated by Django 4.1.3 on 2022-12-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0050_alter_bdservice_bdt_rate_pickedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickedorder',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
